name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Etapa 1: Application Build
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Compile Java project
        run: mvn clean install

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkinglot-jar
          path: target/parkinglot-0.0.1-SNAPSHOT.jar

      # Etapa 2: Docker Build
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t duvangt/pamela-galvis:v1.0 .

      - name: Push Docker image
        run: docker push duvangt/pamela-galvis:v1.0