name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  application-build:
    name: Application Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java project
        run: mvn clean install

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkinglot-jar
          path: target/parkinglot-0.0.1-SNAPSHOT.jar

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: application-build  # Espera a que termine el anterior
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: parkinglot-jar
          path: target/

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t duvangt/pamela-galvis:v1.0 .

      - name: Push Docker image
        run: docker push duvangt/pamela-galvis:v1.0
        
        
